---
title: Daniel + Erin Furr - Family Blog
baseURL: "/"
params:
  layout_style: overflow
  palette: green
  header:
    title: Furr Family Blog
    tagline: Header Tagline
    profile_img: "/images/Selene and Daniel.jpg"
    bg: light
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
